### ISSUE TITLE
internal server error nach rails 6 upgrade

### ISSUE THREAD

**Issue by nimaai** [Madek/Madek#423]
concerns `webapp`, `admin-webapp` is ok. assumption: cookies...

```
Feb 22 13:14:17 madek-staging madek-webapp[47987]: [FATAL, 2023-02-22T13:14:17+00:00] [13:14:17] [443] [111.92.74.12]
Feb 22 13:14:17 madek-staging madek-webapp[47987]: [139B blob data]
Feb 22 13:14:17 madek-staging madek-webapp[47987]: [13:14:17] [443] [111.92.74.12]
Feb 22 13:14:17 madek-staging madek-webapp[47987]: [13:14:17] [443] [111.92.74.12] app/controllers/application_controller.rb:78:in `current_user'
Feb 22 13:14:17 madek-staging madek-webapp[47987]: [13:14:17] [443] [111.92.74.12] app/controllers/application_controller.rb:46:in `init_layout_data_presenter'
Feb 22 13:14:17 madek-staging madek-webapp[47987]: [118B blob data]
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/json-2.3.0/lib/json/common.rb:156:in `parse'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.1/lib/active_support/json/decoding.rb:23:in `decode'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/middleware/cookies.rb:551:in `load'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/middleware/cookies.rb:587:in `deserialize'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/middleware/cookies.rb:676:in `parse'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/middleware/cookies.rb:490:in `[]'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/middleware/session/cookie_store.rb:114:in `get_cookie'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/middleware/session/cookie_store.rb:89:in `block (2 levels) in unpacked_cookie_data'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/middleware/session/abstract_store.rb:53:in `stale_session_check!'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/middleware/session/cookie_store.rb:88:in `block in unpacked_cookie_data'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rack-2.2.6.2/lib/rack/request.rb:69:in `fetch'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rack-2.2.6.2/lib/rack/request.rb:69:in `fetch_header'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/middleware/session/cookie_store.rb:87:in `unpacked_cookie_data'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/middleware/session/cookie_store.rb:81:in `block in extract_session_id'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/middleware/session/abstract_store.rb:53:in `stale_session_check!'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/middleware/session/cookie_store.rb:80:in `extract_session_id'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/request/session.rb:54:in `block in id'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/request/session.rb:53:in `fetch'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/request/session.rb:53:in `id'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/request/session.rb:72:in `id'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rack-2.2.6.2/lib/rack/session/abstract/id.rb:329:in `current_session_id'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rack-2.2.6.2/lib/rack/session/abstract/id.rb:335:in `session_exists?'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/request/session.rb:203:in `exists?'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/request/session.rb:226:in `load_for_read!'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/request/session.rb:92:in `[]'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /madek/server/webapp/app/controllers/application_controller.rb:78:in `current_user'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /madek/server/webapp/app/controllers/application_controller.rb:46:in `init_layout_data_presenter'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.1/lib/active_support/callbacks.rb:427:in `block in make_lambda'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.1/lib/active_support/callbacks.rb:198:in `block (2 levels) in halting'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/abstract_controller/callbacks.rb:34:in `block (2 levels) in <module:Callbacks>'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.1/lib/active_support/callbacks.rb:199:in `block in halting'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.1/lib/active_support/callbacks.rb:512:in `block in invoke_before'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.1/lib/active_support/callbacks.rb:512:in `each'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.1/lib/active_support/callbacks.rb:512:in `invoke_before'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.1/lib/active_support/callbacks.rb:115:in `block in run_callbacks'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actiontext-6.1.7.1/lib/action_text/rendering.rb:20:in `with_renderer'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actiontext-6.1.7.1/lib/action_text/engine.rb:59:in `block (4 levels) in <class:Engine>'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.1/lib/active_support/callbacks.rb:126:in `instance_exec'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.1/lib/active_support/callbacks.rb:126:in `block in run_callbacks'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.1/lib/active_support/callbacks.rb:137:in `run_callbacks'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/abstract_controller/callbacks.rb:41:in `process_action'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_controller/metal/rescue.rb:22:in `process_action'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_controller/metal/instrumentation.rb:34:in `block in process_action'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.1/lib/active_support/notifications.rb:203:in `block in instrument'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.1/lib/active_support/notifications/instrumenter.rb:24:in `instrument'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.1/lib/active_support/notifications.rb:203:in `instrument'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_controller/metal/instrumentation.rb:33:in `process_action'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_controller/metal/params_wrapper.rb:249:in `process_action'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/activerecord-6.1.7.1/lib/active_record/railties/controller_runtime.rb:27:in `process_action'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/abstract_controller/base.rb:165:in `process'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionview-6.1.7.1/lib/action_view/rendering.rb:39:in `process'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_controller/metal.rb:190:in `dispatch'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_controller/metal.rb:238:in `block in action'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /madek/server/webapp/config/application.rb:71:in `block in <class:Application>'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/middleware/show_exceptions.rb:53:in `render_exception'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/middleware/show_exceptions.rb:36:in `rescue in call'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/middleware/show_exceptions.rb:31:in `call'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/railties-6.1.7.1/lib/rails/rack/logger.rb:37:in `call_app'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/railties-6.1.7.1/lib/rails/rack/logger.rb:26:in `block in call'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.1/lib/active_support/tagged_logging.rb:99:in `block in tagged'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.1/lib/active_support/tagged_logging.rb:37:in `tagged'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/activesupport-6.1.7.1/lib/active_support/tagged_logging.rb:99:in `tagged'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/railties-6.1.7.1/lib/rails/rack/logger.rb:26:in `call'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/middleware/remote_ip.rb:81:in `call'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/middleware/request_id.rb:26:in `call'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rack-2.2.6.2/lib/rack/method_override.rb:24:in `call'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rack-2.2.6.2/lib/rack/runtime.rb:22:in `call'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/middleware/executor.rb:14:in `call'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/rack-2.2.6.2/lib/rack/sendfile.rb:110:in `call'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/actionpack-6.1.7.1/lib/action_dispatch/middleware/host_authorization.rb:142:in `call'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/railties-6.1.7.1/lib/rails/engine.rb:539:in `call'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/puma-6.0.1/lib/puma/configuration.rb:268:in `call'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/puma-6.0.1/lib/puma/request.rb:93:in `block in handle_request'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/puma-6.0.1/lib/puma/thread_pool.rb:340:in `with_force_shutdown'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/puma-6.0.1/lib/puma/request.rb:92:in `handle_request'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/puma-6.0.1/lib/puma/server.rb:429:in `process_client'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/puma-6.0.1/lib/puma/server.rb:232:in `block in run'
Feb 22 13:14:17 madek-staging madek-webapp[47987]:   /home/madek/.asdf/installs/ruby/3.1.3/lib/ruby/gems/3.1.0/gems/puma-6.0.1/lib/puma/thread_pool.rb:147:in `block in spawn_thread'
```

**Comment by nimaai** [comment]
to take look at: https://guides.rubyonrails.org/upgrading_ruby_on_rails.html#upgrading-from-rails-5-2-to-rails-6-0

**Comment by nimaai** [comment]
can be reproduced locally. cause: old cookies created by rails 5.2

**Comment by nimaai** [comment]
problem solution suggestion: changing the secret: 

https://stackoverflow.com/questions/25031985/rails-4-upgrade-jsonparseerror-for-old-sessions

**Comment by nimaai** [comment]
work done so far: https://github.com/Madek/madek/commit/50c6f4433edd901c12184b686b847105d2d99272

@DrTom now only update of the secrets in `deploy` is required. i leave it to you as i don't know what is used to create them.

**Comment by DrTom** [comment]
I am not quite happy with changing the secret to facilitate this. That would mean, that this has to be done for every instance of madek. Is there a better way to fix this? Maybe enable the old method or catch this exceptions and delete the cookie and do a redirect to root.

**Comment by DrTom** [comment]
`:hybrid` should do the trick, see 

https://github.com/rails/rails/issues/15111#issuecomment-43136055

**Comment by nimaai** [comment]
`:hybrid` does not work anymore. next steps:
1. see if `:hybrid` can work somehow
2. catch the exception then delete the cookie
3. rename the cookie
4. change the secret as last resort

**Comment by nimaai** [comment]
implemented solution nr. 2: https://github.com/Madek/madek/commit/28c34552cac05b133efca76ee1c5a2b2ac47a2ba
