### ISSUE TITLE
Webapp: Applikationslog entspammen

### ISSUE THREAD

**Issue by urs-van-binsbergen** [Madek/Madek#574]
Jeder Request wirft folgende Warnung:
```
Apr 09 08:08:14 zhdk-madek-prod madek-webapp[3647671]: [WARN , 2024-04-09T08:08:14+00:00] [08:08:14] [443] [xxx.xxx.xxx.xxx] Session cookie not found.
```

Weiterer häufiger Fehler:
```
Apr 09 08:08:14 zhdk-madek-prod madek-webapp[3647671]: [FATAL, 2024-04-09T08:08:14+00:00] [08:08:14] [443] [xxx.xxx.xxx.xxx]
Apr 09 08:08:14 zhdk-madek-prod madek-webapp[3647671]: [08:08:14] [443] [xxx.xxx.xxx.xxx] ActionController::UnpermittedParameters (found unpermitted parameter: :permissions):
Apr 09 08:08:14 zhdk-madek-prod madek-webapp[3647671]: [08:08:14] [443] [xxx.xxx.xxx.xxx]
Apr 09 08:08:14 zhdk-madek-prod madek-webapp[3647671]: [08:08:14] [443] [xxx.xxx.xxx.xxx] app/controllers/concerns/resource_list_params.rb:103:in `check_allowed_filter_params!'
Apr 09 08:08:14 zhdk-madek-prod madek-webapp[3647671]: [08:08:14] [443] [xxx.xxx.xxx.xxx] app/controllers/concerns/resource_list_params.rb:80:in `block in process_list_params'
Apr 09 08:08:14 zhdk-madek-prod madek-webapp[3647671]: [08:08:14] [443] [xxx.xxx.xxx.xxx] app/controllers/concerns/resource_list_params.rb:79:in `process_list_params'
Apr 09 08:08:14 zhdk-madek-prod madek-webapp[3647671]: [08:08:14] [443] [xxx.xxx.xxx.xxx] app/controllers/concerns/resource_list_params.rb:64:in `resource_list_params'
Apr 09 08:08:14 zhdk-madek-prod madek-webapp[3647671]: [08:08:14] [443] [xxx.xxx.xxx.xxx] app/controllers/concerns/resource_list_params.rb:23:in `both_list_params'
Apr 09 08:08:14 zhdk-madek-prod madek-webapp[3647671]: [08:08:14] [443] [xxx.xxx.xxx.xxx] app/controllers/concerns/resource_list_params.rb:46:in `resource_list_by_type_param'
Apr 09 08:08:14 zhdk-madek-prod madek-webapp[3647671]: [08:08:14] [443] [xxx.xxx.xxx.xxx] app/controllers/collections_controller.rb:296:in `determine_list_conf'
Apr 09 08:08:14 zhdk-madek-prod madek-webapp[3647671]: [08:08:14] [443] [xxx.xxx.xxx.xxx] app/controllers/collections_controller.rb:45:in `show'
Apr 09 08:08:14 zhdk-madek-prod madek-webapp[3647671]: [08:08:14] [443] [xxx.xxx.xxx.xxx] app/controllers/collections_controller.rb:32:in `context'
Apr 09 08:08:14 zhdk-madek-prod madek-webapp[3647671]: [08:08:14] [443] [xxx.xxx.xxx.xxx] lib/madek/middleware/audit.rb:27:in `call'
```

(Weitere zu eruieren anhand Journal)

**Comment by nimaai** [comment]
`Session cookie not found` : https://github.com/Madek/madek/commit/6e7e663dd44049ae9fd46b20f0168ebe8701baca

**Comment by nimaai** [comment]
Debug statement for prod: https://github.com/Madek/madek/commit/1d29544b63186f81724e98dea3ec862ad9e10318

to be removed after the actual fix

**Comment by nimaai** [comment]
die exception kommt berechtigterweise weil in diesem fall eine ungültige filterkombination für `type=all` geschickt wird. meines wissens nach kann man sich so was in UI nicht zusammenklicken. ein crawler im spiel?

**Comment by phoettli** [comment]
ist der Absender identifizierbar ?

**Comment by phoettli** [comment]
@nimaai tataaaaa !
in den Non-JavaScript-Version gibt es Beispiellinks mit Parametern, die aber nicht gültig sind, wenn im Tab "All" aufgerufen:
<img width="250" alt="image" src="https://github.com/Madek/Madek/assets/42544602/ff213757-a433-4017-8975-16a10944a682">

diese sollten entfernt oder besser, dem aktuell gewählten Tab entsprechend angepasst werden (bei "all" z.B. nichts ausser `search`

**Comment by nimaai** [comment]
> Aber andere Bots kümmern sich möglicherweise nicht um die Sperre.

ja, der kaputte link kommt von: bytedance.com

```
47.128.17.46 - - [17/Apr/2024:14:28:56 +0000] "GET /sets/691a1676-6d5f-4d5c-a41a-dcd9610a03e7/context/project_archive?lang=en&list%5Bfilter%5D=%7B%0A%20%20%22media_files%22%3A%20%5B%0A%20%20%20%20%7B%0A%20%20%20%20%20%20%22key%22%3A%20%22content_type%22%2C%0A%20%20%20%20%20%20%22value%22%3A%20%22image%2Fjpeg%22%0A%20%20%20%20%7D%0A%20%20%5D%0A%7D&list%5Blayout%5D=list&list%5Border%5D=title%20DESC&list%5Bpage%5D=1&list%5Bper_page%5D=12&list%5Bshow_filter%5D=true&type=all HTTP/1.1" 500 4888 "-" "Mozilla/5.0 (Linux; Android 5.0) AppleWebKit/537.36 (KHTML, like Gecko) Mobile Safari/537.36 (compatible; Bytespider; spider-feedback@bytedance.com)" "Zh_cqMXzrvBkHLnia1FSOAAAAM4"
```

**Comment by urs-van-binsbergen** [comment]
Theoretisch könnte es sein, dass man den Ausdruck zusätzlich noch nicht-URL-encoded angeben sollte: 
`
Disallow: /*?*list%5Bfilter%5D=*
Disallow: /*?*list[filter]=*
`
(der Stern am Ende ist übrigens überflüssig, aber stört wohl auch nicht)

**Comment by phoettli** [comment]
@urs-van-binsbergen 
> Vermutlich sollte man den Ausdruck zusätzlich noch nicht-URL-encoded angeben

Google jedenfalls braucht den nicht

**Comment by belafonte** [comment]
Denke ich habe endlich das richtige Dokument zum Thema gefunden.
Daraus entnehme ich auch, dass die URLs scheinbar unencoded in der robots.txt stehen sollen.

https://www.rfc-editor.org/rfc/rfc9309.html#name-protocol-definition

**Comment by phoettli** [comment]
kaputte Links werden hier gefixt: #582
