### ISSUE TITLE
File-Upload wird häufig durch einen Fehler-Hinweis abgeschlossen

### ISSUE THREAD

**Issue by phoettli** [Madek/Madek#669]
File-Upload zählt während Upload Prozentzahlen hoch.
Zum Schluss erscheint nach 100% der Hinweis "verarbeiten" manchmal, manchmal wird aber ein "Fehler!" ausgegeben, obwohl der Upload erfolgreich war:

<img width="448" alt="image" src="https://github.com/user-attachments/assets/e8c88d55-0ba9-4230-900c-3cb5d0063214">

**Comment by urs-van-binsbergen** [comment]
Kleines Update gemacht, welche beim Upload mehr Infos in die Browser-Konsole loggt (ist gemerget, und wird gerade auf TEST und TEST-BLANK deployed, wobei nur auf letzterem relevant). 

Wenn der Fehler auftritt, bitte F12-Konsole öffnen (oder diese schon vor dem Upload öffnen). Bei Fehler sollte sowas stehen: 
![image](https://github.com/user-attachments/assets/6a085d38-aa3f-4b54-9ee2-30e6cfc83855)

Dann bitte Screenshot der Konsole machen (analog dem obigen Screenshot). Bitte auch den Inhalt des HTML-Batzens als Text kopieren. 
![image](https://github.com/user-attachments/assets/0b3afd78-110a-4cfe-b13e-5342a44f46ca)

Theoretisch könnte ein Grund für das Problem auch sein, dass die Prozentzahl nicht berechnet werden kann. Neu steht dann "??%", und in der Konsole ein Fehler dieser Art: 
![image](https://github.com/user-attachments/assets/d132112b-06a7-4fda-8064-abc843dbfc0b)

**Comment by phoettli** [comment]
@urs-van-binsbergen die Dokumentation bis zum Fehler sieht man auch hier #667

**Comment by urs-van-binsbergen** [comment]
Das ist der Fehler im Journal:

```
Jan 27 08:23:43 zhdk-madek-prod madek-webapp[1848]: [ERROR, 2025-01-27T08:23:43+00:00] [08:23:41] [443] [IP-ADDRESS-REMOVED]
Jan 27 08:23:43 zhdk-madek-prod madek-webapp[1848]: [08:23:41] [443] [IP-ADDRESS-REMOVED] NoMethodError (undefined method `round' for nil:NilClass):
Jan 27 08:23:43 zhdk-madek-prod madek-webapp[1848]: [08:23:41] [443] [IP-ADDRESS-REMOVED]
Jan 27 08:23:43 zhdk-madek-prod madek-webapp[1848]: [08:23:41] [443] [IP-ADDRESS-REMOVED] app/presenters/presenters/media_files/media_file.rb:60:in `conversion_progress'
Jan 27 08:23:43 zhdk-madek-prod madek-webapp[1848]: [08:23:41] [443] [IP-ADDRESS-REMOVED] app/presenters/presenter.rb:39:in `block in full_dump'
Jan 27 08:23:43 zhdk-madek-prod madek-webapp[1848]: [08:23:41] [443] [IP-ADDRESS-REMOVED] app/presenters/presenter.rb:36:in `map'
Jan 27 08:23:43 zhdk-madek-prod madek-webapp[1848]: [08:23:41] [443] [IP-ADDRESS-REMOVED] app/presenters/presenter.rb:36:in `full_dump'
Jan 27 08:23:43 zhdk-madek-prod madek-webapp[1848]: [08:23:41] [443] [IP-ADDRESS-REMOVED] app/presenters/presenters/modules/dump_helpers.rb:15:in `deal_with_obj_type'
Jan 27 08:23:43 zhdk-madek-prod madek-webapp[1848]: [08:23:41] [443] [IP-ADDRESS-REMOVED] app/presenters/presenters/modules/dump_helpers.rb:8:in `dump_recur'
Jan 27 08:23:43 zhdk-madek-prod madek-webapp[1848]: [08:23:41] [443] [IP-ADDRESS-REMOVED] app/presenters/presenter.rb:49:in `block in full_dump'
Jan 27 08:23:43 zhdk-madek-prod madek-webapp[1848]: [08:23:41] [443] [IP-ADDRESS-REMOVED] app/presenters/presenter.rb:36:in `map'
Jan 27 08:23:43 zhdk-madek-prod madek-webapp[1848]: [08:23:41] [443] [IP-ADDRESS-REMOVED] app/presenters/presenter.rb:36:in `full_dump'
Jan 27 08:23:43 zhdk-madek-prod madek-webapp[1848]: [08:23:41] [443] [IP-ADDRESS-REMOVED] app/presenters/presenter.rb:29:in `dump'
Jan 27 08:23:43 zhdk-madek-prod madek-webapp[1848]: [08:23:41] [443] [IP-ADDRESS-REMOVED] lib/application_responder.rb:18:in `serialize_resource'
Jan 27 08:23:43 zhdk-madek-prod madek-webapp[1848]: [08:23:41] [443] [IP-ADDRESS-REMOVED] lib/responders/json_responder.rb:5:in `to_json'
Jan 27 08:23:43 zhdk-madek-prod madek-webapp[1848]: [08:23:41] [443] [IP-ADDRESS-REMOVED] app/controllers/concerns/responders_setup.rb:17:in `block (2 levels) in respond_with_custom'
Jan 27 08:23:43 zhdk-madek-prod madek-webapp[1848]: [08:23:41] [443] [IP-ADDRESS-REMOVED] app/controllers/concerns/responders_setup.rb:9:in `respond_with_custom'
Jan 27 08:23:43 zhdk-madek-prod madek-webapp[1848]: [08:23:41] [443] [IP-ADDRESS-REMOVED] app/controllers/concerns/controller_helpers.rb:39:in `represent'
Jan 27 08:23:43 zhdk-madek-prod madek-webapp[1848]: [08:23:41] [443] [IP-ADDRESS-REMOVED] app/controllers/modules/media_entries/upload.rb:27:in `create'
```

Offenbar ist kurzzeitig das Feld `zencoder_jobs.progress` NULL. 

Erstaunlich ist, dass die Transaktion durchgeht (also das File ganz normal gespeichert wird), obwohl der HTTP Status 500 ist (gemäss Apache-Log und gemäss `audited_responses`)

**Comment by DrTom** [comment]
> Offenbar ist kurzzeitig das Feld zencoder_jobs.progress NULL.

Das ist ja interessant, wir setzen das auf `0.0` per default in der DB; aber einen not null constraint hat es nicht. Vermutlich schickt Zencoder bevor es überhaupt "richtig" mit der encodierung anfängt einen Status mit dieser NULL drin. 

Tja, unser Beitrag zu "the billion dollar mistake" ;-)

**Comment by DrTom** [comment]
> Erstaunlich ist, dass die Transaktion durchgeht (also das File ganz normal gespeichert wird), obwohl der HTTP Status 500 ist
nicht unbedingt erstaunlich; dem Zencoder ist es wohl egal ob das zwischendrin  eine Null hat und vielleicht 500 ergibt; selbst wenn er welche davon abbekommt (das ist noch fraglich) sind solche APIs oft "resilient" programmiert

**Comment by urs-van-binsbergen** [comment]
ea161e8b46e3a1648eea8238e46734f595ee08cd

**Comment by phoettli** [comment]
bei mir zeigt es jetzt keine Upload-Prozente:
zuerst erscheint "Warten", dann ist plötzlich der Upload abgeschlossen, allerdings ohne Statusmeldung.

upload:
<img width="167" height="239" alt="Image" src="https://github.com/user-attachments/assets/6d6b22b0-10af-4fd0-8715-517b9f3f5888" />

abgeschlossen:
<img width="167" height="214" alt="Image" src="https://github.com/user-attachments/assets/e40c8eb0-268e-405e-90d5-e6f9aa6972f4" />
